name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # diario 00:00 UTC
  workflow_dispatch:      # ejecución manual

permissions:
  contents: write
  actions: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Repo
        run: |
          git remote add upstream https://github.com/TinchoAlmuzara/PanelLocalProjections
          git fetch upstream

      - name: Fast-forward merge if possible
        id: ff
        run: |
          git checkout main
          git merge --ff-only upstream/main || echo "ff_failed=true" >> $GITHUB_OUTPUT

      - name: Push Changes to Fork
        if: steps.ff.outputs.ff_failed != 'true'
        run: git push origin main

      - name: Create PR when histories diverge
        if: steps.ff.outputs.ff_failed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Merge upstream/main into main"
          title: "Sync fork: upstream/main → main"
          body: "Auto-PR porque no se pudo fast-forward."
          base: main
          branch: chore/sync-upstream
